# Generated by Django 3.2.2 on 2023-10-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Message'},
        ),
    ]
